# Generated by Django 5.1 on 2025-02-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nysc_church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nyscattendance',
            name='active',
        ),
        migrations.RemoveField(
            model_name='nyscnewcomer',
            name='active',
        ),
    ]
