# Generated by Django 5.1 on 2025-02-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nysc_church', '0002_remove_nyscattendance_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='NYSCSession',
        ),
        migrations.RenameIndex(
            model_name='nyscsession',
            new_name='nysc_church_id_85ceb0_idx',
            old_name='nysc_church_id_6c575c_idx',
        ),
    ]
