# Generated by Django 5.1.6 on 2025-02-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc_church', '0003_rename_session_nyscsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyscattendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nyscnewcomer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
