# Generated by Django 5.1 on 2024-11-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOGECDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['-name'], name='logec_logec_name_d5fa8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LOGECDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=50)),
                ('posted_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-title'],
                'indexes': [models.Index(fields=['-title'], name='logec_logec_title_10c051_idx')],
            },
        ),
        migrations.CreateModel(
            name='LOGECSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bible_text', models.CharField(max_length=200)),
                ('preacher', models.CharField(max_length=200)),
                ('sermon', models.TextField()),
                ('posted_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-title'],
                'indexes': [models.Index(fields=['-title'], name='logec_logec_title_71e003_idx')],
            },
        ),
        migrations.CreateModel(
            name='LOGECPendingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('Akure', 'Akure'), ('Ikare', 'Ikare')], default='Akure', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logec.logecdepartment')),
            ],
            options={
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['-name'], name='logec_logec_name_4dda45_idx')],
            },
        ),
    ]
