# Generated by Django 5.1 on 2024-11-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logec', '0002_logecquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGECMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('Akure', 'Akure'), ('Ikare', 'Ikare')], default='Akure', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logec.logecdepartment')),
            ],
            options={
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['-name'], name='logec_logec_name_21b7e7_idx')],
            },
        ),
    ]
