# Generated by Django 5.1 on 2024-11-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logec', '0003_logecmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGECSermonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='logecpendingmember',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='logecdonation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='logecquestion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='logecsermon',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='logecdonation',
            name='logec_logec_title_10c051_idx',
        ),
        migrations.RemoveIndex(
            model_name='logecquestion',
            name='logec_logec_date_bf56a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='logecsermon',
            name='logec_logec_title_71e003_idx',
        ),
        migrations.AddIndex(
            model_name='logecdonation',
            index=models.Index(fields=['-id'], name='logec_logec_id_91ab9a_idx'),
        ),
        migrations.AddIndex(
            model_name='logecquestion',
            index=models.Index(fields=['-id'], name='logec_logec_id_c4cb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='logecsermon',
            index=models.Index(fields=['-id'], name='logec_logec_id_d0e235_idx'),
        ),
        migrations.AddField(
            model_name='logecsermoncomment',
            name='sermon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logec.logecsermon'),
        ),
        migrations.DeleteModel(
            name='LOGECPendingMember',
        ),
        migrations.AddIndex(
            model_name='logecsermoncomment',
            index=models.Index(fields=['-id'], name='logec_logec_id_536c3c_idx'),
        ),
    ]
