# Generated by Django 5.1 on 2024-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logec', '0004_logecsermoncomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logecmember',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logecmember',
            name='branch',
            field=models.CharField(default='Akure', max_length=200),
        ),
        migrations.CreateModel(
            name='LOGECNewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('office_address', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(default='Akure', max_length=200)),
                ('is_single', models.BooleanField(default=True)),
                ('is_member', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='logec_logec_id_d58bf2_idx')],
            },
        ),
        migrations.DeleteModel(
            name='LOGECDepartment',
        ),
    ]
