# Generated by Django 5.1 on 2024-11-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logec', '0005_alter_logecmember_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logecnewmember',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
