# Generated by Django 5.1 on 2024-09-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
