# Generated by Django 5.1 on 2024-09-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_alter_question_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
